import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: LayoutProps<"/">) => (
  <html className={`dark ${inter.variable}`} data-theme="dark" lang="en">
    <body>{children}</body>
  </html>
);

export default RootLayout;
